name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main  # Adjust this as necessary for your project
      
env:
  REGISTRY: europe-west1-docker.pkg.dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}
        
    - name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
#      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonserver:latest --push .
##
#    - name: Deploy to Google Cloud Run
#      run: |
#        gcloud run deploy pythonserver --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonserver:latest --platform managed --region europe-west2 --allow-unauthenticated
#
 
