name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main  # Adjust this as necessary for your project

jobs:
  auth:
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
  
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@latest

    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonserver:latest --push .
#
#    - name: Deploy to Google Cloud Run
#      run: |
#        gcloud run deploy pythonserver --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonserver:latest --platform managed --region europe-west2 --allow-unauthenticated
#
 
