name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Cloud Registry
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '296.0.0'  # Update this to the latest stable version
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonserver:latest --push .

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy pythonserver --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pythonserver --platform managed --region europe-west2 --allow-unauthenticated
